config/routes.rb
Rails.application.routes.draw do
  get 'goals/new'

  get 'sessions/new'

  get 'users/new'
  
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/goals',   to:  'goals#index'
  post   '/goals',   to:  'goals#create'
  delete '/goals',   to:  'goals#destroy'
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :goals do

    member do
      get 'complete'
      get 'active_again'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
	belongs_to	:user

	validates	:title, :description, :priority, :user_id, presence: true 
	validates	:priority, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  before_create :confirmation_token
  has_many      :goals
  before_save { self.email = email.downcase }
  validates :first_name, :last_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format:{ with: VALID_EMAIL_REGEX },
                    uniqueness:{ case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def full_name
  "#{first_name} #{last_name}"
  end

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end

  private
    def confirmation_token
      if self.confirm_token.blank?
          self.confirm_token = SecureRandom.urlsafe_base64.to_s
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  helper_method :sort_column, :sort_direction

  def new
  	@goal = Goal.new
  end

  def show
  	@goal = current_user.goals.find params[:id] 
  end

  def index
  	@goal = current_user.goals.order(sort_column + ' ' + sort_direction).where(complited: false) 
    @goal_completed = current_user.goals.order(sort_column + ' ' + sort_direction).where(complited: true) 
  end

  def create
    @goal = Goal.create(goal_params)

    if @goal.save
      redirect_to goals_path
    else
      render "new"
    end 
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    @goals = Goal.all

    respond_to do |format|
      format.html { redirect_to goals_path }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  def edit
    @goal = current_user.goals.find params[:id]
  end

  def update
    @goal = Goal.find(params[:id])

    if @goal.update_attributes(goal_params)
      redirect_to goals_path
    else
      render 'edit'
    end
  end

  def complete
    @goal = Goal.find(params[:id])
    @goal.update_attributes(complited: true) 
    redirect_to goals_path
  end

  def active_again
    @goal = Goal.find(params[:id])
    @goal.update_attributes(complited: false) 
    redirect_to goals_path
  end

  private

    def sort_column
    Goal.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end

  def goal_params
    params.require(:goal).permit(:user_id, :title, :description, :priority, :complited, :due_date)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
      user = User.find_by_email(params[:session][:email])
      
      if user && user.authenticate(params[:session][:password])
      if user.email_confirmed
         log_in user
        redirect_to goals_path
      else
        flash.now[:error] = 'Please activate your account by following the 
        instructions in the account confirmation email you received to proceed'
        render 'new'
      end
      else
        flash.now[:error] = 'Invalid email or password' 
        render 'new'
      end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
        @user = User.new(user_params)    
      if @user.save
        UserMailer.registration_confirmation(@user).deliver
        flash[:success] = "Please confirm your email address to continue"
        redirect_to login_url
      else
        flash[:error] = "Something went wrong!"
        render 'new'
      end
  end

  def confirm_email
    user = User.find_by_confirm_token(params[:id])
    if user
      user.email_activate
      flash[:success] = "Welcome to the Task Manager! Your email has been confirmed.
      Please sign in to continue."
      redirect_to login_url
    else
      flash[:error] = "Sorry. User does not exist"
      redirect_to login_url
    end
end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Task Manager"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_goal.html.erb
<div class="goal">
<li class="goals-list">
    <div class="col-md-3">
      <h4><b><%= link_to goal.title, goal_path(goal) %></b></h4>
    </div>
    <div class="col-md-3">
      <p><%= goal.due_date %></p>
    </div>
  
    <div class="col-md-3">
      <%= goal.priority %>
    </div>
    <div class="col-md-2">
      <b class = 'red'>
      <%= link_to goal_path(goal), method: :delete, data: {confirm: 'Warning! Current goal will be irretrievably removed.'}, :remote => true, :class => 'delete_goal' do %>
      <i class="fa fa-trash-o fa-2x" aria-hidden="true"></i>
      <% end %>
      </b>
      <%= link_to "", edit_goal_path(goal), :class => 'fa fa-pencil-square-o fa-2x' %>
      <%= link_to "", goal_path(goal), :class => 'fa fa fa-eye fa-2x' %>
     
      <% unless goal.complited? %>
       <b class = "green">          
      <%= link_to "", complete_goal_path(goal), :class => 'fa fa-check fa-2x ' %>
    </b>
      <% else  %> 
      <%= link_to "", active_again_goal_path(goal), :class => 'fa fa-repeat fa-2x' %>
      <% end %> 

    </div>
</li>
</div>
<div class="clearfix"></div>

app/views/goals/_goal_form.html.erb
<div class="container">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for @goal do |f| %>
    
    <%= f.hidden_field :user_id, value: current_user.id %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control'%>
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control'%>
      <%= f.label :priority %>
      <%= f.number_field :priority, class: 'form-control', :min => '1', :max => '5'%>
      <%= f.label :due_date %>
      <div class='input-group date' id='datetimepicker'>
        <%= f.text_field :due_date, :required =>true, :value => Date.today, :min => Date.today, class: 'form-control'%>
        <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
        </span>
      </div>
      <script type="text/javascript">
        $(function () {
        var date = new Date();
        var currentMonth = date.getMonth();
        var currentDate = date.getDate();
        var currentYear = date.getFullYear();
        $('#datetimepicker').datetimepicker({
            locale: 'en',
            format: 'YYYY-MM-DD',         
            minDate: new Date(currentYear, currentMonth, currentDate)
          });
        });
      </script> 
    </div>
      <div class="col-md-4 col-md-offset-4">
      <%= f.submit "save", class: "btn btn-primary",data: { disable_with: "Please wait..." } %></p>
    </div>
  </div>
</div>
<% end %>

app/views/goals/_sort.html.erb
<div class="sort_header">
		<div class="col-md-3">
     	<p><%=sortable "title"%></p>
    </div>
     <div class="col-md-3">
      	<p><%=sortable "due_date"%></p>
    </div>
    <div class="col-md-3">
   		<p><%= sortable "priority" %></p>
    </div>
    <div class="col-md-3">
    	<p>Actions</p>
    </div>
</div>
<div class="clearfix"></div>

app/views/goals/destroy.js.erb
$('.delete_goal').bind('ajax:success', function() {
   $(this).closest('li').fadeOut();
});

app/views/goals/edit.html.erb
<% provide(:title, 'Edit') %>
<h1>Edit</h1>
<%= render 'goal_form' %> 

app/views/goals/index.html.erb
  <h3>Not completed</h3>
         <ul>
         <% if @goal.empty? %>
          <b>
            <span>You dont have any goals, start to reach them today!</span>
          </b>
         <% else @goals %>
          <%= render 'sort' %> 
          <% @goal.each do |goal| %>
            <%= render partial: 'goal', object: goal %> 
          <% end %>
         <% end %>

      </ul>
      <%= link_to 'Create new goal', new_goal_path,  class: 'btn btn-primary' %>
      <h3>Completed</h3>
      <ul>
        <% if @goal_completed.empty? %>
          <b>
            <span> You dont have any completed goals!</span>
          </b>
         <% else @goal_completed %>
         <%= render 'sort' %> 
          <% @goal_completed.each do |goal| %>
            <%= render partial: 'goal', object: goal %> 
          <% end %>
         <% end %>
      </ul>

app/views/goals/new.html.erb
<% provide(:title, 'new goal') %>
<h1>New Goal</h1>
<%= render 'goal_form' %> 

app/views/goals/show.html.erb
<h1><%= @goal.title %></h1>
<div class="container">
	<div class="description-body"><%= @goal.description %></div>
</div>

<div class= "Back">
	<%= link_to 'Back to list', goals_path,  class: 'btn btn-primary' %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
 
  <nav>
    <ul>
    	<b>
      <li><%= link_to "About",   about_path %></li>
     
      <li><%= link_to "Contact", contact_path %></li>
  		</b>
  		
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
<% if logged_in? %>
  
      <%= link_to "TaskM", goals_path, id: "logo" %>
  
  <% else %>
  
      <%= link_to "TaskM", root_path, id: "logo" %>
  <% end %>

    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li>
          <%= link_to "Home", goals_path%>
        </li>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
        <% end %>
        
        <li><%= link_to "Help",    help_path %></li>
        <% if logged_in? %>
        <li>
          <%= link_to "Log out", logout_path, method: :delete %>
        </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= render 'layouts/shim' %>
    
  </head>
  <body>

 
    <%= render 'layouts/header' %>	
    <div class="container">
      <%= yield %>
    </div>
    <div class="container">
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  This is task management system for people who want achieve their goals and be successful in life!
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Task Manager developer if you have some offers or for another reason - <b>denis_wander@ukr.net.</b> Click <%= link_to "here",    help_path %> if you need some help.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Need some help?</h1>
<p>
  We are ready to solve your problem at any time! Our Mail - <b>task_manager.support@ukr.net</b>
</p>

app/views/static_pages/home.html.erb
	<div class="center jumbotron">
  		<h1>Welcome to Task Manager</h1>

  		<h2>
    		Join us and achieve your goals every day!
  		</h2>

  	<%= link_to "Sign up now!", signup_path , class: "btn btn-lg btn-primary" %>
	</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 signUp">
    <%= form_for(@user, url: signup_path) do |f| %>
    <%= render 'shared/error_messages' %>
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.first_name %>